language: java
dist: trusty
services: 
    - mysql
jdk: oraclejdk8
sudo: required
before_install:
    - git clone https://github.com/gchq/event-logging.git
    - cd event-logging
    - ./gradlew clean build publishToMavenLocal
