language: java
dist: trusty
#services:
  #- docker
jdk: oraclejdk8
sudo: required #to ensure we get a VM rather than a container for more memory and for all the apt-get stuff

env:
  global:
    - CURRENT_STROOM_DEV_VERSION=v6.0.0
    - DOCKER_REPO=gchq/stroom
    - DOCKER_COMPOSE_VERSION=1.13.0
    
before_install:
    #Print out the current versions before we change them
  - docker --version
  - docker-compose --version
    #remove the old docker version
  - sudo apt-get -y remove docker docker-engine
    #extra stuff required for docker CE
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    #Add the apt repo for docker
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install linux-image-extra-$(uname -r) linux-image-extra-virtual apt-transport-https ca-certificates curl software-properties-common docker-ce
  - docker --version
    #remove the old docker-compose
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker-compose --version


# We run a script to build dependencies and do database setup
#install: "./.travis.install.sh"
    
install: echo "skip 'gradle assemble' step to speed up build"

# Increase the size of the heap
before_script:
  - "echo $JAVA_OPTS"
  - "export JAVA_OPTS=-Xmx1024m"
  - "git clone https://github.com/gchq/urlDependencies-plugin.git"
  - "pushd urlDependencies-plugin"
  - "./gradlew clean build publishToMavenLocal"
  - "popd"
  - "git clone https://github.com/gchq/stroom-resources.git"
  - "pushd stroom-resources/dev-resources/compose"
    #start all the services we need to run the integration tests in stroom
  - "docker-compose -f stroom-dbs.yml up -d"
  - "popd"

# We're running this as a script because our build is either too silent or too chatty and TravisCI will kill either way.
#script: travis_wait 30 ./gradlew -Pversion=$TRAVIS_TAG downloadUrlDependencies clean build -x test shadowJar
script: ./gradlew -Pversion=$TRAVIS_TAG downloadUrlDependencies clean build shadowJar

# Push to DockerHub. The username and password were added using the Travis CLI.
# The configuration below will only push an image if the branch being built is master.
after_success:
  - export DATE_ONLY="$(date +%y%m%d)"
  - export DATE_TIME="$(date +%y%m%d%H%M%S)"
    #establish what version of stroom we are building
  - |
    if [ -n "$TRAVIS_TAG" ]; then
      #this is a tagged build so use the tag as the version
      export STROOM_VERSION=${TRAVIS_TAG};
    else
      export STROOM_VERSION=${CURRENT_STROOM_DEV_VERSION};
    fi
  - |
    if [ "$TRAVIS_EVENT_TYPE" == "cron" ]; then
      export SPECIFIC_TAG="--tag=${DOCKER_REPO}:${STROOM_VERSION}-${DATE_ONLY}-DAILY";
      export FLOATING_TAG="";
    elif [ -n "$TRAVIS_TAG" ]; then
      export SPECIFIC_TAG="--tag=${DOCKER_REPO}:${TRAVIS_TAG}";
      export FLOATING_TAG="";
    elif [ "$TRAVIS_BRANCH" == "dev" ]; then
      export SPECIFIC_TAG="";
      export FLOATING_TAG="--tag=${DOCKER_REPO}:${STROOM_VERSION}-SNAPSHOT";
    fi
  - |
    if [ -n "$TRAVIS_BRANCH" == "dev" || -n "$TRAVIS_TAG" || "$TRAVIS_EVENT_TYPE" == "cron" ]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      docker build ${SPECIFIC_TAG} ${FLOATING_TAG} stroom-app/. ;
      #docker build --tag=gchq/stroom:dev-latest stroom-app/. ;
      docker push gchq/stroom;
    fi

# Push to GitHub releases for any tagged commit - the key was generated by the Travis CLI.
deploy:
  provider: releases
  api_key:
    secure: xUPJboaSjxs3lKCqXu5zYzdV75S+lu5EZ6RD+RigmQ5MSjeuFBhoBKYaJUz+ejaoFLfF8WSUbmlgTeRMK7QI4MtCqjy08uREext8sm0behMREz4mmPEb9eTLu+WfIXFbnOPG4pKzkAtHA3x+hNQN3EWga1Xa2WXGYdOuK1B7vnrYOPo9D2zI12JCaoXt0KUQ70LwE07uwBIuDn+0EbVsAftFatJh7jZXeMsE8GmdcwsM/DObKjtTLBH3bpE8pPPJ8H0ssuIsQk2jHg91cTgrlB0q0K1a5TjeKKMGPMY6S6UR9cB7l7FqCVEsOd7T/ExdKp1TflMRyuuKG9ACBXTaegfBt7pP7KYEpYtidC5p/b1J4cYvazVTIfo6m93wnOJAdcD1XeMqNIQZVSxNuflmgM8xZz+UuqPBF4dk3Z5Eoh4sTH+t6WmZY6YoIt6tRMQ8xRyvkTfzsfYUtsV4csyeB2oy5s/GJmYGtR5GjjK6T+mh8RmI/DVWW50ubdFaAYYdz+LSgfpGhBXEBkYPghMSjYiPDsJStXsOwRSQbR9LmRO7jk08PxxT33pLr8Ct0HoQPpSP8Fom4q1ntrZBDjeHL8/2cQtRKqUg3X9G0sU7aW5i0G4U7BE42Xkcc/VVJhFrVbRj5+xQq70uMyUmHi2Wh+mBQSY+ZlBrvr6FRcKj42E=
  file: stroom-app/build/libs/stroom-app-all.jar
  skip_cleanup: true
  on:
    tags: true

#clean out gradle caches as per travis docs
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

# Cache dependencies to speed up the build
cache:
  directories:
    - .autoconf
    - $HOME/.m2
    - libs
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
