server:
    type: simple
    applicationContextPath: /
    adminContextPath: /admin
    connector:
        type: http
        port: 8080

logging:
    level: INFO
    loggers:
        stroom.statistics: INFO
    appenders:
        - type: console
          threshold: INFO
          logFormat: "%-6level [%d{HH:mm:ss.SSS}] [%t] %logger{5} - %X{code} %msg %n"
          timeZone: UTC
uiPath: src/main/resources/ui