server:
  type: simple
  applicationContextPath: /
  adminContextPath: /admin
  connector:
    type: http
    port: 8080

logging:
  level: INFO
  level: ERROR
  loggers:
    "stroom":
      level: INFO
      additive: true
  appenders:
    - type: console

uiPath: ./ui/