server:
  applicationContextPath: ${APPLICATION_CONTEXT_PATH:- /}
  adminContextPath: ${ADMIN_CONTEXT_PATH:- /admin}
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081
  #The following two lines stop the logging of requests to the web server as this gets quite noisy with
  #lots of background rpc calls going on
  requestLog:
    appenders: []

logging:
  level: ERROR
  loggers:
    stroom: INFO
    io.dropwizard: INFO
    org.ehcache: INFO
    org.eclipse.jetty: INFO
    org.flywaydb: INFO
  appenders:
    - type: console
      logFormat: "%-6level [%d{HH:mm:ss.SSS}] [%t] %logger{5} - %X{code} %msg %n"
      timeZone: UTC
