server:
  type: simple
  applicationContextPath: /
  adminContextPath: /admin
  connector:
    type: http
    port: 8080

logging:
  level: ERROR
  loggers:
    "stroom":
      level: INFO
      additive: true
  appenders:
    - type: console
      logFormat: "%-6level [%d{HH:mm:ss.SSS}] [%t] %logger{5} - %X{code} %msg %n"
      timeZone: UTC

zookeeperUrl: localhost:2181
hostNameOrIpAddress: http://localhost:8080