server:
  applicationContextPath: ${APPLICATION_CONTEXT_PATH:- /}
  adminContextPath: ${ADMIN_CONTEXT_PATH:- /admin}
  applicationConnectors:
    - type: http
      port: ${STROOM_APP_PORT:-8080}
  adminConnectors:
    - type: http
      port: ${STROOM_ADMIN_PORT:-8081}

logging:
  level: ${STROOM_LOGGING_LEVEL:- ERROR}
  loggers:
    stroom: INFO
    io.dropwizard: INFO
    org.eclipse.jetty: INFO
    org.flywaydb: INFO
    "event-logger":
      level: INFO
      additive: false
      appenders:
        - type: file
          logFormat: "%msg%n"
          currentLogFilename: event.log
          archivedLogFilenamePattern: event-%d{yyyy-MM-dd}.log
          timeZone: UTC
  appenders:
    - type: console
      logFormat: "%-6level [%d{HH:mm:ss.SSS}] [%t] %logger{5} - %X{code} %msg %n"
      timeZone: UTC
    - type: file
      logFormat: "%-6level [%d{HH:mm:ss.SSS}] [%t] %logger{35} - %X{code} %msg %n"
      currentLogFilename: stroom.log
      archivedLogFilenamePattern: stroom-%d{yyyy-MM-dd}.log
      archivedFileCount: 10
      timeZone: UTC
