server:
  type: simple
  applicationContextPath: /
  adminContextPath: /admin
  connector:
    type: http
    port: 8080
  #The following two lines stop the logging of requests to the web server as this gets quite noisy with
  #lots of background rpc calls going on
  requestLog:
    appenders: []

logging:
  level: ERROR
  loggers:
    stroom: INFO
    stroom.resources.query.v1.SqlStatisticsQueryResource: DEBUG
    io.dropwizard: INFO
    org.eclipse.jetty: INFO
    org.flywaydb: INFO
  appenders:
    - type: console
      logFormat: "%-6level [%d{HH:mm:ss.SSS}] [%t] %logger{5} - %X{code} %msg %n"
      timeZone: UTC