name: Java CI with Gradle

on:
  push:
    #branches: [ master ]
  pull_request:
    #branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      # Static env vars

      # Github runners limited to 2 cores, 7Gb RAM
      # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
      MAX_WORKERS="3"

    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set Environment Variables
      id: set_env_var
      run: |
        #VERSION="SNAPSHOT"
        #if [[ $VERSION == *"beta"* ]]; then IS_PRE='true'; else IS_PRE='false'; fi
        #echo ::set-output name=version::${VERSION}
        #echo ::set-output name=prerelease::${IS_PRE}

        # Set variables in github's env file which are then read into each subsequent step
        {
          # Map the GITHUB env vars to our own
          echo "BUILD_DIR=${GITHUB_WORKSPACE}"
          echo "BUILD_COMMIT=${GITHUB_SHA}"
          if [[ ${GITHUB_REF} =~ ^refs/tags/ ]]; then
            # strip off the 'refs/tags/' bit
            echo "BUILD_TAG=${GITHUB_REF#refs/tags/}"
          fi
          if [[ ${GITHUB_REF} =~ ^refs/heads/ ]]; then
            # strip off the 'ref/heads/' bit
            echo "BUILD_BRANCH=${GITHUB_REF#refs/heads/}"
          fi
          if [[ ${GITHUB_REF} =~ ^refs/pulls/ ]]; then
            echo "BUILD_IS_PULL_REQUEST=true"
          else
            echo "BUILD_IS_PULL_REQUEST=false"
          fi
        } >> $GITHUB_ENV

        echo "git branch: [$(git rev-parse --abbrev-ref HEAD)]"

    - name: Build Environment Info
      run: |
        echo "docker version:           [$(docker --version)]"
        echo "docker-compose version:   [$(docker-compose --version)]"
        echo "git version:              [$(git --version)]"
        echo "GITHUB_WORKSPACE:         [$GITHUB_WORKSPACE]"
        echo "GITHUB_REF:               [$GITHUB_REF]"
        echo "GITHUB_SHA:               [$GITHUB_SHA]"
        echo "BUILD_DIR:                [$BUILD_DIR]"
        echo "BUILD_TAG:                [$BUILD_TAG]"
        echo "BUILD_BRANCH:             [$BUILD_BRANCH]"
        echo "BUILD_COMMIT:             [$BUILD_COMMIT]"
        echo "BUILD_IS_PULL_REQUEST:    [$BUILD_IS_PULL_REQUEST]"
        echo "STROOM_RESOURCES_GIT_TAG: [$STROOM_RESOURCES_GIT_TAG]"
        echo "PWD:                      [$PWD]"
        echo "HOME:                     [$HOME]"

    - name: Run full build
      run: |
        pushd "${BUILD_DIR}" > /dev/null
        echo -e "${GREEN}Running ${BLUE}travis.script.sh${NC}"
        ./travis.script.sh
        echo -e "${GREEN}Finished running build script${NC}"


